# This file is parsed with ERB first, then YAML.
#
# Jets::Config.project_namespace is special value results in using the project namespace. Example :
# table_namespace: <%= Jets.config.project_namespace %>
# This is the default value.

development:

  # endpoint: http://localhost:8000 # comment out if want to test with real dynamodb
  # on AWS. You can also set the DYNAMODB_ENDPOINT environment variable.
  # You can also are actually deploying a development environment is to
  # change bin/server and export DYNAMODB_ENDPOINT=http://localhost:8000 at the top
  # there.

test:
  endpoint: http://localhost:8000

  # See https://docs.aws.amazon.com/general/latest/gr/rande.html
production:
# endpoint: https://dynamodb.us-west-2.amazonaws.com
